spring:
  datasource:
    url: jdbc:postgresql://postgres-docgen:5432/docgen_db
    username: docgen_user

  kafka:
    bootstrap-servers: kafka:29092

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8180/realms/eflo/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
