package com.eflo.workflow.domain.enums;

public enum TaskActionType {
    CREATED, ASSIGNED, STARTED, UPDATED, COMPLETED,
    APPROVED, REJECTED, DELEGATED, ESCALATED, SKIPPED,
    DOCUMENT_UPLOADED, DATA_ENTERED, CANCELLED, REASSIGNED,
    APPROVAL_STARTED
}
