package com.eflo.user.domain.enums;

public enum ActivityType {
    LOGIN,
    LOGOUT,
    PROFILE_UPDATE,
    PASSWORD_CHANGE,
    ROLE_ASSIGNED,
    ROLE_ASSIGNMENT,
    ROLE_REVOKED,
    ROLE_REVOCATION,
    BUSINESS_UNIT_ASSIGNED,
    BUSINESS_UNIT_ASSIGNMENT,
    BUSINESS_UNIT_REMOVED,
    BUSINESS_UNIT_REMOVAL,
    PRIMARY_BUSINESS_UNIT_CHANGE,
    DEACTIVATED,
    REACTIVATED,
    CREATED,
    USER_CREATED,
    DELETED,
    USER_DELETED,
    STATUS_CHANGE,
    HIERARCHY_CHANGE
}
